### ISSUE TITLE
Set container of component port with python

### ISSUE THREAD

**Issue by Nelson1905** [labs4capella/python4capella#221]
Hi,

I want to change container of this component port (the new container will be System Function B) with python4capella but I didn't fund functions to do that.

Do you know how to do that.
![image](https://github.com/user-attachments/assets/92143d71-4e31-4ab4-9f0b-8b4eb861f808)

**Comment by ylussaud** [comment]
You can Move the FunctionInputPort like this:
```
mySourceSystemFunction = ...
#change with your own FunctionInputPort here
myFunctionInputPort = mySourceSystemFunction.get_inputs().get(0)
myTargetSystemFunction = ...
myTargetSystemFunction.get_inputs().add(myFunctionInputPort)
```
Since an EObject can only be contained by one EObject it will move the FunctionInputPort.
You will need to run this code in a [transaction](https://github.com/labs4capella/python4capella/blob/master/doc/org.eclipse.python4capella.doc/doc/user/general/TipsAndTricks.textile#modify-your-capella-model) in order to modify your model.

**Comment by Nelson1905** [comment]
Yes it work thanks you !!!
