### ISSUE TITLE
Support headless mode with Team 4 Capella

### ISSUE THREAD

**Issue by Aurelien-Pin** [labs4capella/python4capella#34]
While executing scripts in headless mode with Team 4 Capella, we will need to provide credentials to the script in order to connect to the repository

**Comment by ylussaud** [comment]
We tested the headless mode with T4C and now it works if the credentials are saved in the project. In order to be able to provide the credentials from Python4Capella we would need an explicit depedency to T4C. That would imply to have a dedicated plugin that can't be built with github actions.

I will had documentation to explain how to store credentials.

**Comment by ylussaud** [comment]
This issue will be closed once I added the documentation. For the other solution a modification is needed in T4C (see VP-5789) and will be released later.
